services:
  primo-devenv:
    build: .
    ports:
      - "8003:8003"
    volumes:
      - ./primo-explore/custom:/app/primo-explore/custom
    environment:
      # Prevents BrowserSync from trying to open a browser inside the container
      - BROWSER=none
    command: ["--view", "${VIEW_CODE}", "--proxy", "https://cuny-${CAMPUS}.primo.exlibrisgroup.com:443"]
